// customers.js
export const CustomerSettings = [
  {
    id: 1,
    name: 'Kirkwall',
    email: 'test@kirkwall.io',
    phone: '',
    metric: ['temp', 'hum', 'rctemp', 'humidity'],
  },
  {
    id: 2,
    name: 'Grand Farm',
    email: 'pmo@grandfarm.com',
    phone: '',
    metric: [
      'temperature',
      'percent_humidity',
      'wind_speed',
      'soil_moisture',
      'rain_15_min_inches',
      'leaf_wetness',
    ],
  },
  {
    id: 3,
    name: 'Watchdog Protect',
    emails: 'trey@watchdogprotect.com',
    phones: '',
    metric: ['temp', 'hum'],
  },
  // {
  //   id: 4,
  //   name: "Rivercity",
  //   email: "",
  //   phone: "",
  //   metric: ["rctemp", "humidity"],
  // },
  // {
  //     id: 5,
  //     name: "RJ Energy",
  //     email: "russell@rjenergysolutions.com",
  //     phone: "",
  //     metric: ["", ""],
  //   },
  {
    id: 6,
    name: 'ImpriMed',
    email: 'jerrycromarty@imprimedicine.com',
    phone: '',
    metric: [
      'imFreezerOneTemp',
      'imFreezerOneHum',
      'imFreezerTwoTemp',
      'imFreezerTwoHum',
      'imFreezerThreeTemp',
      'imFreezerThreeHum',
      'imFridgeOneTemp',
      'imFridgeOneHum',
      'imFridgeTwoTemp',
      'imFridgeTwoHum',
      'imIncubatorOneTemp',
      'imIncubatorOneHum',
      'imIncubatorTwoTemp',
      'imIncubatorTwoHum',
    ],
  },
];
