name: Run Backend Cron Job


'on':
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: {}


jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install
      - name: Run cron job script
        run: node src/Backend/server.mjs
        env:
          TWILIO_ACCOUNT_SID: '${{ secrets.TWILIO_ACCOUNT_SID }}'
          TWILIO_AUTH_TOKEN: '${{ secrets.TWILIO_AUTH_TOKEN }}'
          TWILIO_PHONE_NUMBER: '${{ secrets.TWILIO_PHONE_NUMBER }}'
          SENDGRID_API_KEY: '${{ secrets.SENDGRID_API_KEY }}'

